// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getNotes: () => __TAURI_INVOKE<Note[]>("get_notes"),
	readNoteContent: (notePath: string) => __TAURI_INVOKE<string>("read_note_content", { notePath }),
	createNote: (noteTitle: string, notePath: string, noteParentPath: string | null) => __TAURI_INVOKE<Note>("create_note", { noteTitle, notePath, noteParentPath }),
};

/* Types */
export type Note = {
	id: number,
	path: string,
	title: string,
	icon: string | null,
	cover_image: string | null,
	parent_path: string | null,
	archived: boolean,
	modified_at: string,
};

