// Whether the sidebar is a strip or a panel, remembered across restarts (#226).
//
// Shadcn's provider writes a `sidebar:state` cookie for this — a SvelteKit
// pattern that wants a server to read it back on the next render. There is
// none, so the sidebar opened expanded on every launch no matter what the GM
// last did. That mattered little while collapsing merely hid a panel the
// [[Icon Rail]] stood beside; now that collapsed *is* the strip, it is a state
// a GM may want to live in.
//
// This lives outside `components/ui/sidebar/` on purpose. Those files are
// generated by `shadcn-svelte` and a regeneration overwrites them, which would
// silently restore the cookie and take this behaviour with it. The provider
// reaches this through its own `open`/`onOpenChange` props, which is the seam
// upstream already offers.

export const SIDEBAR_STATE_STORAGE_KEY = "grimoire:sidebar-open";

/** The GM's last collapsed-or-expanded, or expanded if they have no last. */
export function readSidebarOpen(): boolean {
  if (typeof localStorage === "undefined") return true;
  try {
    // Only the string this module writes for collapsed can mean collapsed.
    // Anything else — absent, corrupted, half-written, or left by an older
    // build — reads expanded, because the strip is not a state to put a GM in
    // by accident.
    return localStorage.getItem(SIDEBAR_STATE_STORAGE_KEY) !== "false";
  } catch {
    return true;
  }
}

export function persistSidebarOpen(open: boolean): void {
  if (typeof localStorage === "undefined") return;
  try {
    localStorage.setItem(SIDEBAR_STATE_STORAGE_KEY, String(open));
  } catch {
    // Storage disabled or full — the state just won't survive a restart, which
    // is where this started.
  }
}
